name: Build
on: [push]
jobs:
  Run-Jupyter-Notebooks:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v3
      - name: Run Python notebook
        run: python -c 'print("Hello Worldzz")'  
        with:
          python-version: "3.10"
     