name: Build
on: [push]
permissions:
  pages: write      # to deploy to Pages
  id-token: write   # to verify the deployment originates from an appropriate source
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
      - name: Install Python packages
        run: pip install -r requirements.txt
      - name: Generate figures and tables
        run: python build.py
      - name: Save artifacts
        uses: actions/upload-artifact@v3
        with:
          name: figures-and-tables
          path: output/
          if-no-files-found: error
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: Install web dependencies
        run: npm install
        working-directory: web
      - name: Setup Pages
        id: setup-pages
        uses: actions/configure-pages@v2
      - name: Build website
        run: BASE_PATH="${{ steps.setup-pages.outputs.base_path }}" npm run build
        working-directory: web
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: web/build/
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
