name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v3
      - name: Install Python packages
        run: pip install -r requirements.txt
      - name: Generate figure JSON
        run: python build.py
      - name: Save figure JSON
        uses: actions/upload-artifact@v3
        with:
          name: figures-and-tables
          path: output/
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: Install web dependencies
        run: npm install
        working-directory: web
      - name: Build website
        run: npm run build
        working-directory: web
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: web/build/
  deploy:
    needs: build
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Setup Pages
      uses: actions/configure-pages@v2
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
