name: Build
on: [push]
jobs:
  Run-Jupyter-Notebooks:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Generate data (Parquet)
        run: Rscript ingest.r
      - name: Generate figure JSON
        run: python create_figure_json.py
        